"""add password to alumnos

Revision ID: 1278e0e1651c
Revises: 8fd1c5c29370
Create Date: 2026-03-21 10:07:20.599031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1278e0e1651c'
down_revision: Union[str, Sequence[str], None] = '8fd1c5c29370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumnos', sa.Column('password', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'alumnos', ['matricula'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alumnos', type_='unique')
    op.drop_column('alumnos', 'password')
    # ### end Alembic commands ###
