"""crear tabla alumnos

Revision ID: 8fd1c5c29370
Revises: 
Create Date: 2026-03-21 09:32:57.691470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd1c5c29370'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=True),
    sa.Column('apellido_materno', sa.String(length=100), nullable=True),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumnos_id'), 'alumnos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alumnos_id'), table_name='alumnos')
    op.drop_table('alumnos')
    # ### end Alembic commands ###
